<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260607074941 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE anne_universitaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(9) NOT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL, is_current BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1035A2EFA4D60759 ON anne_universitaire (libelle)');
        $this->addSql('CREATE TABLE deliberation (id UUID NOT NULL, moyenne_generale NUMERIC(5, 2) DEFAULT NULL, total_credits INT DEFAULT NULL, credits_valides INT DEFAULT NULL, decision VARCHAR(20) NOT NULL, mention_globale VARCHAR(30) DEFAULT NULL, observations TEXT DEFAULT NULL, date_deliberation DATE DEFAULT NULL, is_publie BOOLEAN NOT NULL, etudiant_id INT NOT NULL, semestre_id INT NOT NULL, annee_universitaire_id INT NOT NULL, delibere_par_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D5B283DDEAB1A3 ON deliberation (etudiant_id)');
        $this->addSql('CREATE INDEX IDX_8D5B2835577AFDB ON deliberation (semestre_id)');
        $this->addSql('CREATE INDEX IDX_8D5B283544BFD58 ON deliberation (annee_universitaire_id)');
        $this->addSql('CREATE INDEX IDX_8D5B2836DAEEC09 ON deliberation (delibere_par_id)');
        $this->addSql('CREATE TABLE enseignant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, prenom VARCHAR(100) NOT NULL, matricule VARCHAR(15) NOT NULL, telephone VARCHAR(15) DEFAULT NULL, grade VARCHAR(30) NOT NULL, specialite VARCHAR(100) NOT NULL, date_embauche DATE NOT NULL, statut VARCHAR(20) NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81A72FA112B2DC9C ON enseignant (matricule)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81A72FA1A76ED395 ON enseignant (user_id)');
        $this->addSql('CREATE TABLE etudiant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, prenom VARCHAR(100) NOT NULL, matricule VARCHAR(15) NOT NULL, date_naissance DATE NOT NULL, lieu_naissance VARCHAR(100) NOT NULL, nationalite VARCHAR(60) NOT NULL, telephone VARCHAR(15) DEFAULT NULL, genre VARCHAR(1) NOT NULL, photo VARCHAR(255) DEFAULT NULL, annee_entree INT NOT NULL, statut VARCHAR(20) NOT NULL, user_id UUID NOT NULL, niveau_id INT NOT NULL, filiere_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_717E22E312B2DC9C ON etudiant (matricule)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_717E22E3A76ED395 ON etudiant (user_id)');
        $this->addSql('CREATE INDEX IDX_717E22E3B3E9C81 ON etudiant (niveau_id)');
        $this->addSql('CREATE INDEX IDX_717E22E3180AA129 ON etudiant (filiere_id)');
        $this->addSql('CREATE TABLE filiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, code VARCHAR(10) NOT NULL, description TEXT DEFAULT NULL, responsable_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2ED05D9E6C6E55B5 ON filiere (nom)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2ED05D9E77153098 ON filiere (code)');
        $this->addSql('CREATE INDEX IDX_2ED05D9E53C59D72 ON filiere (responsable_id)');
        $this->addSql('CREATE TABLE matiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(15) NOT NULL, credit INT NOT NULL, coefficient NUMERIC(5, 2) NOT NULL, type VARCHAR(20) NOT NULL, note_cc_poids NUMERIC(3, 2) NOT NULL, note_ex_poids NUMERIC(3, 2) NOT NULL, is_active BOOLEAN NOT NULL, semestre_id INT NOT NULL, enseignant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9014574A77153098 ON matiere (code)');
        $this->addSql('CREATE INDEX IDX_9014574A5577AFDB ON matiere (semestre_id)');
        $this->addSql('CREATE INDEX IDX_9014574AE455FCC0 ON matiere (enseignant_id)');
        $this->addSql('CREATE TABLE niveau (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(10) NOT NULL, code VARCHAR(5) NOT NULL, credits_requis INT NOT NULL, filiere_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4BDFF36B77153098 ON niveau (code)');
        $this->addSql('CREATE INDEX IDX_4BDFF36B180AA129 ON niveau (filiere_id)');
        $this->addSql('CREATE TABLE note (id UUID NOT NULL, note_cc NUMERIC(5, 2) DEFAULT NULL, note_examen NUMERIC(5, 2) DEFAULT NULL, note_finale NUMERIC(5, 2) DEFAULT NULL, mention VARCHAR(2) DEFAULT NULL, is_absent_cc BOOLEAN NOT NULL, is_absent_examen BOOLEAN NOT NULL, date_saisie TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_modification TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, etudiant_id INT NOT NULL, matiere_id INT NOT NULL, semestre_id INT NOT NULL, saisie_par_id UUID DEFAULT NULL, modifie_par_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CFBDFA14DDEAB1A3 ON note (etudiant_id)');
        $this->addSql('CREATE INDEX IDX_CFBDFA14F46CD258 ON note (matiere_id)');
        $this->addSql('CREATE INDEX IDX_CFBDFA145577AFDB ON note (semestre_id)');
        $this->addSql('CREATE INDEX IDX_CFBDFA14C74AC7FE ON note (saisie_par_id)');
        $this->addSql('CREATE INDEX IDX_CFBDFA14553B2554 ON note (modifie_par_id)');
        $this->addSql('CREATE TABLE reclamation (id UUID NOT NULL, motif TEXT NOT NULL, type_reclamation VARCHAR(30) NOT NULL, statut VARCHAR(20) NOT NULL, reponse TEXT DEFAULT NULL, date_soumission TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_limite TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_traitement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, etudiant_id INT NOT NULL, note_id UUID NOT NULL, traite_par_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CE606404DDEAB1A3 ON reclamation (etudiant_id)');
        $this->addSql('CREATE INDEX IDX_CE60640426ED0855 ON reclamation (note_id)');
        $this->addSql('CREATE INDEX IDX_CE606404167FABE8 ON reclamation (traite_par_id)');
        $this->addSql('CREATE TABLE semestre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(10) NOT NULL, date_debut_saisie DATE DEFAULT NULL, date_fin_saisie DATE DEFAULT NULL, is_cloture BOOLEAN NOT NULL, niveau_id INT NOT NULL, annee_universitaire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_71688FBCB3E9C81 ON semestre (niveau_id)');
        $this->addSql('CREATE INDEX IDX_71688FBC544BFD58 ON semestre (annee_universitaire_id)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, login_attempts INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('ALTER TABLE deliberation ADD CONSTRAINT FK_8D5B283DDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deliberation ADD CONSTRAINT FK_8D5B2835577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deliberation ADD CONSTRAINT FK_8D5B283544BFD58 FOREIGN KEY (annee_universitaire_id) REFERENCES anne_universitaire (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE deliberation ADD CONSTRAINT FK_8D5B2836DAEEC09 FOREIGN KEY (delibere_par_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enseignant ADD CONSTRAINT FK_81A72FA1A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE etudiant ADD CONSTRAINT FK_717E22E3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE etudiant ADD CONSTRAINT FK_717E22E3B3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveau (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE etudiant ADD CONSTRAINT FK_717E22E3180AA129 FOREIGN KEY (filiere_id) REFERENCES filiere (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE filiere ADD CONSTRAINT FK_2ED05D9E53C59D72 FOREIGN KEY (responsable_id) REFERENCES enseignant (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE matiere ADD CONSTRAINT FK_9014574A5577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE matiere ADD CONSTRAINT FK_9014574AE455FCC0 FOREIGN KEY (enseignant_id) REFERENCES enseignant (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE niveau ADD CONSTRAINT FK_4BDFF36B180AA129 FOREIGN KEY (filiere_id) REFERENCES filiere (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14DDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA145577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14C74AC7FE FOREIGN KEY (saisie_par_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14553B2554 FOREIGN KEY (modifie_par_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT FK_CE606404DDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT FK_CE60640426ED0855 FOREIGN KEY (note_id) REFERENCES note (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT FK_CE606404167FABE8 FOREIGN KEY (traite_par_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE semestre ADD CONSTRAINT FK_71688FBCB3E9C81 FOREIGN KEY (niveau_id) REFERENCES niveau (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE semestre ADD CONSTRAINT FK_71688FBC544BFD58 FOREIGN KEY (annee_universitaire_id) REFERENCES anne_universitaire (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE deliberation DROP CONSTRAINT FK_8D5B283DDEAB1A3');
        $this->addSql('ALTER TABLE deliberation DROP CONSTRAINT FK_8D5B2835577AFDB');
        $this->addSql('ALTER TABLE deliberation DROP CONSTRAINT FK_8D5B283544BFD58');
        $this->addSql('ALTER TABLE deliberation DROP CONSTRAINT FK_8D5B2836DAEEC09');
        $this->addSql('ALTER TABLE enseignant DROP CONSTRAINT FK_81A72FA1A76ED395');
        $this->addSql('ALTER TABLE etudiant DROP CONSTRAINT FK_717E22E3A76ED395');
        $this->addSql('ALTER TABLE etudiant DROP CONSTRAINT FK_717E22E3B3E9C81');
        $this->addSql('ALTER TABLE etudiant DROP CONSTRAINT FK_717E22E3180AA129');
        $this->addSql('ALTER TABLE filiere DROP CONSTRAINT FK_2ED05D9E53C59D72');
        $this->addSql('ALTER TABLE matiere DROP CONSTRAINT FK_9014574A5577AFDB');
        $this->addSql('ALTER TABLE matiere DROP CONSTRAINT FK_9014574AE455FCC0');
        $this->addSql('ALTER TABLE niveau DROP CONSTRAINT FK_4BDFF36B180AA129');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14DDEAB1A3');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14F46CD258');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA145577AFDB');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14C74AC7FE');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14553B2554');
        $this->addSql('ALTER TABLE reclamation DROP CONSTRAINT FK_CE606404DDEAB1A3');
        $this->addSql('ALTER TABLE reclamation DROP CONSTRAINT FK_CE60640426ED0855');
        $this->addSql('ALTER TABLE reclamation DROP CONSTRAINT FK_CE606404167FABE8');
        $this->addSql('ALTER TABLE semestre DROP CONSTRAINT FK_71688FBCB3E9C81');
        $this->addSql('ALTER TABLE semestre DROP CONSTRAINT FK_71688FBC544BFD58');
        $this->addSql('DROP TABLE anne_universitaire');
        $this->addSql('DROP TABLE deliberation');
        $this->addSql('DROP TABLE enseignant');
        $this->addSql('DROP TABLE etudiant');
        $this->addSql('DROP TABLE filiere');
        $this->addSql('DROP TABLE matiere');
        $this->addSql('DROP TABLE niveau');
        $this->addSql('DROP TABLE note');
        $this->addSql('DROP TABLE reclamation');
        $this->addSql('DROP TABLE semestre');
        $this->addSql('DROP TABLE "user"');
    }
}
