<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260608225104 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_log (id UUID NOT NULL, action VARCHAR(100) NOT NULL, entite VARCHAR(100) NOT NULL, entite_id VARCHAR(255) DEFAULT NULL, ancienne_valeur JSON DEFAULT NULL, nouvelle_valeur JSON DEFAULT NULL, ip_adresse VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F6E1C0F5A76ED395 ON audit_log (user_id)');
        $this->addSql('CREATE TABLE departement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, code VARCHAR(10) NOT NULL, description TEXT DEFAULT NULL, filiere_id INT DEFAULT NULL, responsable_id INT DEFAULT NULL, chef_departement_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C1765B6377153098 ON departement (code)');
        $this->addSql('CREATE INDEX IDX_C1765B63180AA129 ON departement (filiere_id)');
        $this->addSql('CREATE INDEX IDX_C1765B6353C59D72 ON departement (responsable_id)');
        $this->addSql('CREATE INDEX IDX_C1765B63C8805231 ON departement (chef_departement_id)');
        $this->addSql('CREATE TABLE session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, libelle VARCHAR(100) NOT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL, is_active BOOLEAN NOT NULL, semestre_id INT NOT NULL, annee_universitaire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D044D5D45577AFDB ON session (semestre_id)');
        $this->addSql('CREATE INDEX IDX_D044D5D4544BFD58 ON session (annee_universitaire_id)');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_F6E1C0F5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE departement ADD CONSTRAINT FK_C1765B63180AA129 FOREIGN KEY (filiere_id) REFERENCES filiere (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE departement ADD CONSTRAINT FK_C1765B6353C59D72 FOREIGN KEY (responsable_id) REFERENCES enseignant (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE departement ADD CONSTRAINT FK_C1765B63C8805231 FOREIGN KEY (chef_departement_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D45577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D4544BFD58 FOREIGN KEY (annee_universitaire_id) REFERENCES anne_universitaire (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE note ADD session_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14613FECDF FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_CFBDFA14613FECDF ON note (session_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_log DROP CONSTRAINT FK_F6E1C0F5A76ED395');
        $this->addSql('ALTER TABLE departement DROP CONSTRAINT FK_C1765B63180AA129');
        $this->addSql('ALTER TABLE departement DROP CONSTRAINT FK_C1765B6353C59D72');
        $this->addSql('ALTER TABLE departement DROP CONSTRAINT FK_C1765B63C8805231');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT FK_D044D5D45577AFDB');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT FK_D044D5D4544BFD58');
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE departement');
        $this->addSql('DROP TABLE session');
        $this->addSql('ALTER TABLE note DROP CONSTRAINT FK_CFBDFA14613FECDF');
        $this->addSql('DROP INDEX IDX_CFBDFA14613FECDF');
        $this->addSql('ALTER TABLE note DROP session_id');
    }
}
