security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN:       [ROLE_ENSEIGNANT, ROLE_ETUDIANT, ROLE_USER]
        ROLE_ENSEIGNANT:  [ROLE_USER]
        ROLE_ETUDIANT:    [ROLE_USER]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/auth/login$
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

    access_control:
        - { path: ^/api,                roles: public_access, methods: [OPTIONS] }
        - { path: ^/api/auth/login$,    roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register$, roles: PUBLIC_ACCESS }
        - { path: ^/api/audit-logs,     roles: ROLE_ADMIN }
        - { path: ^/api/admin/users,    roles: ROLE_SUPER_ADMIN }
        - { path: ^/api/admin,          roles: ROLE_ADMIN }
        - { path: ^/api/filieres,       roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/niveaux,        roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/semestres,      roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/annees,         roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/matieres,       roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/enseignants,    roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/etudiants,      roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/deliberations,  roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/departements,   roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/sessions,       roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/statistiques,   roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/notes,          roles: ROLE_ENSEIGNANT, methods: [POST, PUT, DELETE] }
        - { path: ^/api,                roles: IS_AUTHENTICATED_FULLY }