security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/auth/login
            stateless: true
            json_login:
                check_path: /api/auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        # Routes publiques
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }

        # Routes Super Admin uniquement
        - { path: ^/api/admin/users, roles: ROLE_SUPER_ADMIN }
        - { path: ^/api/audit-logs, roles: ROLE_ADMIN }

        # Routes Admin et Super Admin
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/filieres, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/niveaux, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/semestres, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/annees, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/matieres, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/enseignants, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/etudiants, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/deliberations, roles: ROLE_ADMIN }

        # Routes Enseignant
        - { path: ^/api/notes, roles: ROLE_ENSEIGNANT, methods: [POST, PUT] }

        # Routes authentifiées (lecture pour tous)
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        # Departements
        - { path: ^/api/departements, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/departements, roles: IS_AUTHENTICATED_FULLY, methods: [GET] }

         # Sessions
        - { path: ^/api/sessions, roles: ROLE_ADMIN, methods: [POST, PUT, DELETE] }
        - { path: ^/api/sessions, roles: IS_AUTHENTICATED_FULLY, methods: [GET] }
        # Super Admin
        - { path: ^/api/admin/users, roles: ROLE_SUPER_ADMIN }
